#!/bin/bash

echo "🚀 Uploading Neural Hub Features..."
echo ""
echo "✅ New Features Added:"
echo "   - Functional landing page with email capture"
echo "   - Working dashboard with content management"
echo "   - API route for email subscriptions"
echo "   - Search and filter functionality"
echo "   - Add content modal"
echo "   - Responsive design"
echo ""
echo "📁 Files to upload:"
echo "   - src/app/page.tsx (updated with features)"
echo "   - src/app/dashboard/page.tsx (new dashboard)"
echo "   - src/app/api/subscribe/route.ts (new API)"
echo ""
echo "📋 Upload Instructions:"
echo "1. Go to: https://github.com/andrewuffman/Neural-Hub"
echo "2. Create folder: src/app/dashboard/"
echo "3. Create folder: src/app/api/subscribe/"
echo "4. Upload all the new files"
echo "5. Commit with message: 'Add: Functional dashboard and email capture'"
echo ""
echo "🎯 Your Neural Hub will now have real functionality!" 