#!/bin/bash

echo "🧪 Uploading Test Version..."
echo ""
echo "✅ Test Changes:"
echo "   - Simplified page structure"
echo "   - Fixed navigation links"
echo "   - Removed complex features section"
echo "   - Focus on core functionality"
echo ""
echo "🎯 What to Test:"
echo "   1. Does the page load with gradient background?"
echo "   2. Does 'Try Dashboard' button navigate to /dashboard?"
echo "   3. Does 'Get Started' scroll to email form?"
echo "   4. Does email form work?"
echo ""
echo "📋 Upload Instructions:"
echo "1. Go to: https://github.com/andrewuffman/Neural-Hub"
echo "2. Upload src/app/page.tsx (test version)"
echo "3. Commit with message: 'Test: Simplified page for deployment verification'"
echo "4. Wait for Vercel to redeploy"
echo "5. Check: https://neural-hub-theta.vercel.app"
echo ""
echo "🔍 If it's still white, check:"
echo "   - Vercel build logs for errors"
echo "   - GitHub file content matches local"
echo "   - Browser cache (try incognito mode)" 