#!/bin/bash

echo "🎨 Uploading Clean White Design..."
echo ""
echo "✅ Design Changes:"
echo "   - Clean white/light gray background"
echo "   - Modern minimalistic style"
echo "   - Removed busy purple gradient"
echo "   - Professional color scheme"
echo "   - Added features section back"
echo ""
echo "🔧 Dashboard Fix:"
echo "   - Ensure dashboard page is uploaded"
echo "   - Fix 404 error on /dashboard route"
echo ""
echo "📁 Files to Upload:"
echo "   - src/app/page.tsx (clean white design)"
echo "   - src/app/dashboard/page.tsx (dashboard functionality)"
echo "   - src/app/api/subscribe/route.ts (email API)"
echo ""
echo "📋 Upload Instructions:"
echo "1. Go to: https://github.com/andrewuffman/Neural-Hub"
echo "2. Create folder: src/app/dashboard/ (if it doesn't exist)"
echo "3. Create folder: src/app/api/subscribe/ (if it doesn't exist)"
echo "4. Upload all three files"
echo "5. Commit with message: 'Design: Clean white minimalistic style + dashboard fix'"
echo ""
echo "🎯 What Should Work:"
echo "   - Clean white landing page"
echo "   - 'Try Dashboard' button navigates to /dashboard"
echo "   - Dashboard shows content management interface"
echo "   - Email capture form works" 