#!/bin/bash

echo "🧹 Uploading Clean Neural Hub Files..."
echo ""
echo "✅ Files are now clean and simplified:"
echo "   - No external dependencies (lucide-react, etc.)"
echo "   - No font imports"
echo "   - Basic inline styles only"
echo ""
echo "📋 Upload Instructions:"
echo "1. Go to: https://github.com/andrewuffman/neural-hub"
echo "2. Click 'Add file' → 'Upload files'"
echo "3. Upload these specific files:"
echo "   - src/app/page.tsx (clean version with React import)"
echo "   - src/app/layout.tsx (simplified without fonts)"
echo "   - src/app/globals.css (basic styles)"
echo "4. Commit with message: 'Fix: Remove external dependencies'"
echo ""
echo "🎯 This should resolve the lucide-react import error!" 